[build]
  command = "npm run build"
  publish = "frontend/build"


# Frontend -> Backend proxy:

[[redirects]]
  from = "/api/*"
  to   = "https://bankingexpertbe.netlify.app/.netlify/functions/api/:splat"
  status = 200
  force  = true
